pool:
  vmImage: 'ubuntu-latest'

pr: none

trigger:
  branches:
    include:
      - '*'

variables:
  - group: spi-samples-js-variables

  - name: ARTIFACT_NAME
    value: spi-samples-js
  - name: BRANCH_NAME
    value: $[variables['Build.SourceBranch']]

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: build
        cancelTimeoutInMinutes: 5
        displayName: Build
        steps:
          - task: Npm@1
            displayName: Install dependencies
            inputs:
              command: 'install'

          - task: Npm@1
            displayName: Build project
            inputs:
              command: 'custom'
              customCommand: 'run build'

          - task: Npm@1
            displayName: Run unit tests
            inputs:
              command: 'custom'
              customCommand: 'run test:deploy'

          - task: PublishTestResults@2
            displayName: Publish unit test results
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '**/junit.xml'

          - task: PublishCodeCoverageResults@1
            displayName: 'Publish code coverage results'
            inputs:
              codeCoverageTool: 'Cobertura'
              summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
              reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'

          - publish: $(System.DefaultWorkingDirectory)/build
            artifact: $(ARTIFACT_NAME)
            displayName: Publish Artifact

          - script: ./scripts/failure-alert.py
            env:
              PYTHONUNBUFFERED: '1'
              ALERT_MESSAGE: 'Build pipeline failure'
            displayName: 'Pipeline failure build stage alert'
            condition: failed()

  - ${{ if startsWith(variables['build.sourceBranch'], 'refs/heads/feature/sample-pos-two') }}:
      - stage: deploy
        displayName: Deploy
        jobs:
          - deployment: Deploy_Dev
            environment: cdn-dev
            pool: shared
            workspace:
              clean: all
            strategy:
              runOnce:
                deploy:
                  steps:
                    - checkout: self

                    - download: current
                      artifact: $(ARTIFACT_NAME)
                      displayName: 'Fetch current package from Azure (dev)'

                    - script: make deploy
                      env:
                        ASSUMED_ROLE: $(AWS_ASSUMED_ROLE)
                        ARTIFACT_PATH: $(Pipeline.Workspace)/$(ARTIFACT_NAME)
                        CLOUDFRONT_ID: $(CLOUDFRONT_ID_DEV)
                        S3_BUCKET: $(S3_BUCKET_DEV)
                      displayName: 'Deploy package (dev)'

                    - script: ./scripts/failure-alert.py
                      env:
                        PYTHONUNBUFFERED: '1'
                        ALERT_MESSAGE: 'Deploy pipeline failure (dev)'
                      displayName: 'Pipeline failure deploy stage alert (dev)'
                      condition: failed()
